smpclClassifieldBundle:
    resource: "@smpclClassifieldBundle/Resources/config/routing.yml"
    prefix:   /
    
smpclUserBundle:
    resource: "@smpclUserBundle/Resources/config/routing.yml"
    prefix:   /

smpclThemeBundle:
    resource: "@smpclThemeBundle/Resources/config/routing.yml"
    prefix:   /
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal


# SONATA ROUTINGS
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin